### ISSUE TITLE
Where you ever to find a work around to this?

### ISSUE THREAD

**Issue by Justinlawrence102** [JagCesar/LiveActivityCoreData#1]
Hi! 
I am also developing a live activity and have been trying to access core data in my live activity (it works in the simulator my not on my physical device). While I was trying to find a solution, I came across this repo describing the same problem. 

By any chance did you find a work around/solution for this or is it a lost cause? 
thanks!

**Comment by JagCesar** [comment]
I never found a workaround for it. Talked a bit to Apple folks about it via TSI and they said it *should* work.

Could never figure it out, so ended up only communicating with the Live Activity using the `Activity` framework.

**Comment by Justinlawrence102** [comment]
That’s what I was concerned they would say. Thanks for the responses!

**Comment by JagCesar** [comment]
No worries! Good luck building a live activity!
